wip/experimental: problem: syntax error on compiled entry script
... and app name for appdata is Electron instead of Emerald Wallet..

App threw an error during load
SyntaxError: /Users/ia/dev/etc/emerald-wallet/app/main.js: Invalid number (15:15)
  13 |     if (typeof mode === 'function' || typeof mode === 'undefined') {
  14 |         callback = mode;
> 15 |         mode = 0777 & (~process.umask());
     |                ^
  16 |     }
  17 |
  18 |     if (!callback) {
    at Parser.pp$5.raise (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:4454:13)
    at Parser.readNumber (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:1268:12)
    at Parser.getTokenFromCode (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:1102:21)
    at Parser.readToken (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:776:19)
    at Parser.<anonymous> (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:7214:20)
    at Parser.readToken (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:6011:22)
    at Parser.nextToken (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:766:19)
    at Parser.next (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:691:10)
    at Parser.pp$3.parseMaybeAssign (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:3366:10)
    at Parser.parseMaybeAssign (/Users/ia/dev/etc/emerald-wallet/node_modules/babylon/lib/index.js:6415:20)
^C

----

These changes are just some general experiments and syntax fmt-ing.